version: "2.0"

services:
  sa-frontend:
    build: 
      context: ./sa-frontend
    image: rinormaloku/sentiment-analysis-frontend:local
    ports:
    - "80:80"

  sa-webapp:
    build: 
      context: ./sa-webapp
    image: rinormaloku/sentiment-analysis-web-app:local
    ports:
    - "8080:8080"
    environment:
    - SA_LOGIC_API_URL=http://sa-logic:5000
    links:
    - sa-logic

  sa-logic:
    build:
      context: ./sa-logic
    image: rinormaloku/sentiment-analysis-logic:local
    ports:
    - "5000:5000"